### ISSUE TITLE
Install errror

### ISSUE THREAD

**Issue by zubairahmed-ai** [coqui-ai/stt-model-manager#15]
After following the install instructions and providing my email I get the following error

![image](https://user-images.githubusercontent.com/1317442/127957263-51733f7b-6d56-496f-95a2-0d3e3583e0c0.png)

**Comment by reuben** [comment]
Are there any relevant logs on the console you're running the model manager from?

**Comment by zubairahmed-ai** [comment]
@reuben  No I couldn't find any logs, please let me know where to look for this and I'll send

**Comment by reuben** [comment]
The terminal where you ran `stt-model-manager` from.

**Comment by zubairahmed-ai** [comment]
Nothing I just ran it again, all I get is below

```
stt-model-manager
Installed models: ModelIndex(models=[])
 * Serving Flask app 'coqui_stt_model_manager.server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Current installs: []
Started server listening on http://127.0.0.1:38450 ...
Current installs: []
```

**Comment by reuben** [comment]
Weird, looks like somehow the page is not talking to the server you're running there. Which would explain the error message. Can you verify if, on the page where you click install, in the URL, the `callback_url` parameter matches what's printed on the console in the "Started server" line? In particular the port number should be the same.

**Comment by reuben** [comment]
> Nothing I just ran it again, all I get is below
> 
> ```
> stt-model-manager
> Installed models: ModelIndex(models=[])
>  * Serving Flask app 'coqui_stt_model_manager.server' (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
> Current installs: []
> Started server listening on http://127.0.0.1:38450 ...
> Current installs: []
> ```

Also, just to be sure, when you ran it this time, you tried to install a model right? You didn't just run it without interacting with it.

**Comment by zubairahmed-ai** [comment]
> Weird, looks like somehow the page is not talking to the server you're running there. Which would explain the error message. Can you verify if, on the page where you click install, in the URL, the `callback_url` parameter matches what's printed on the console in the "Started server" line? In particular the port number should be the same.

Yes it does match, I verified it too
it's this one `https://coqui.ai/english/coqui/v0.9.3?callback_url=http://127.0.0.1:38450/install_model&name=English%20STT%20v0.9.3#download`

**Comment by zubairahmed-ai** [comment]
And yes I tried to install the model, there was nothing to interface with since there is no existing model

**Comment by reuben** [comment]
If the URL matches the logs on the terminal, but nothing else gets printed, then it can only be some problem on the website or your browser. Does the browser console have any error in the install page before/after you click install?

**Comment by zubairahmed-ai** [comment]
Good question, yes the console has the following error, not sure what's causing it though

![image](https://user-images.githubusercontent.com/1317442/128182826-00f00cc7-73f4-433f-8d0d-e4013659779b.png)

**Comment by reuben** [comment]
Perhaps an overzealous ad blocker or misconfigured browser (not respecting CORS).

**Comment by zubairahmed-ai** [comment]
You're right about this too, I am using Brave and it's known to block ads, tried this in Chrome and voila!

![image](https://user-images.githubusercontent.com/1317442/128185595-24adceff-d383-4871-9beb-c5a6b5891a85.png)

**Comment by willymateo** [comment]
> Perhaps an overzealous ad blocker or misconfigured browser (not respecting CORS).
This solution also works for me.
