### ISSUE TITLE
Werkzeug >=2.1 removes deprecated run_with_reloader

### ISSUE THREAD

**Issue by Glandos** [coqui-ai/stt-model-manager#35]
Since https://github.com/pallets/werkzeug/commit/a0e15e6c43c585a7e1bc2a3f4c3936083373001b that was published in Werkzeug 2.1, `run_with_reloader` is not exported anymore. The code should be adapted or Werkzeug should be pinned to <2.1 in the meantime.

**Comment by wasertech** [comment]
So this can be closed right?
