### ISSUE TITLE
Model Zoo unavailable (404)

### ISSUE THREAD

**Issue by benpicco** [coqui-ai/stt-model-manager#53]
The link to the [model zoo](https://coqui.ai/models/) no longer works, it's not possible to install a model and there is also no manual installation option (#26)

**Comment by codegraft** [comment]
Just ran into this myself. As a workaround it is possible to POST a model card (https://github.com/coqui-ai/stt-model-manager/blob/8489e2e74b1fbd565c0460f003eff9843f7251a1/coqui_stt_model_manager/modelmanager.py#L237) to `/install_model` with stt-model-manager running.

For example to install the "English STT v1.0.0 (Huge Vocabulary)" model 
``` json
{
    "name": "English STT v1.0.0 (Huge Vocabulary)",
    "language": "en",
    "version": "v1.0.0",
    "creator": "Coqui",
    "acoustic": "https://coqui.gateway.scarf.sh/english/coqui/v1.0.0-huge-vocab/model.tflite",
    "scorer": "https://coqui.gateway.scarf.sh/english/coqui/v1.0.0-huge-vocab/huge-vocabulary.scorer"
}
```

For example on Windows with stt-model-manager running I used curl like this (change 38450 to whatever port stt-model-manager is using):  `curl --header "Content-Type: application/json" --request POST --data "{\"name\": \"English STT v1.0.0 (Huge Vocabulary)\", \"language\": \"en\", \"version\": \"v1.0.0\", \"creator\": \"Coqui\", \"acoustic\": \"https://coqui.gateway.scarf.sh/english/coqui/v1.0.0-huge-vocab/model.tflite\", \"scorer\": \"https://coqui.gateway.scarf.sh/english/coqui/v1.0.0-huge-vocab/huge-vocabulary.scorer\"}"  http://127.0.0.1:38450/install_model`

On Linux the following should do the same (untested)
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"name": "English STT v1.0.0 (Huge Vocabulary)", "language": "en", "version": "v1.0.0", "creator": "Coqui", "acoustic": "https://coqui.gateway.scarf.sh/english/coqui/v1.0.0-huge-vocab/model.tflite", "scorer": "https://coqui.gateway.scarf.sh/english/coqui/v1.0.0-huge-vocab/huge-vocabulary.scorer"}' \
  http://127.0.0.1:38450/install_model
```

**Comment by KnechtNoobrecht** [comment]
And how do i do that without knowing what models exist? And how isn't this solved by now? The documentation still links to this non-existent site and doesn't provide alternatives. This is terrible!

**Comment by reuben** [comment]
See the note in the README, the models are hosted in the releases of this repo: https://github.com/coqui-ai/stt-model-manager#coqui-stt-model-manager
